# Generated by Django 4.1.2 on 2023-06-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_rutuser_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rutuser',
            new_name='rut_user',
        ),
    ]
