# Generated by Django 4.1.2 on 2023-07-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_rutuser_profile_rut_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Comuna'),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mascota', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='nombre mascota')),
                ('edad', models.IntegerField(blank=True, null=True, verbose_name='edad')),
                ('sexo', models.CharField(blank=True, max_length=20, null=True, verbose_name='sexo')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='color mascota')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha_nacimiento')),
                ('raza', models.CharField(blank=True, max_length=30, null=True, verbose_name='raza')),
                ('rut_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rut', to='accounts.profile')),
            ],
        ),
    ]
