# Generated by Django 4.1.2 on 2023-07-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_location_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(blank=True, max_length=100, verbose_name='nombre_vacuna')),
                ('tipo_vacuna', models.CharField(blank=True, max_length=100, verbose_name='tipo vacuna')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mascota')),
            ],
        ),
    ]
