# Generated by Django 5.0 on 2023-12-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_desparacitacion_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='color',
            field=models.CharField(max_length=30, verbose_name='color mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(verbose_name='edad'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='fecha_nacimiento'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='nombre mascota'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=30, verbose_name='raza'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(max_length=20, verbose_name='sexo'),
        ),
    ]
